# openapi2-run.yaml
swagger: '2.0'
info:
  title: api-id
  description: Sample API on API Gateway with a Cloud Run backend
  version: 1.0.0
schemes:
- http
produces:
- application/json
x-google-backend:
  address: https://book-shelf-app-3u3y7l7buq-uc.a.run.app    #url of the backend cloud run 
paths:
  /books:
    get:
      summary: Bookshelf
      operationId: books
      responses:
        '200':
          description: A successful response
          schema:
            type: string
  
  /errors:
    get:
      summary: errors
      operationId: errors
      responses:
        '200':
          description: A successful response
          schema:
            type: string  

  /logs:
    get:
      summary: logs
      operationId: logs
      responses:
        '200':
          description: A successful response
          schema:
            type: string  

  /books/crud:
    get:
      summary: /books/crud
      operationId: books/crud
      responses:
        '200':
          description: A successful response
          schema:
            type: string

  /books/api:
    get:
      summary: /books/api
      operationId: books/api
      responses:
        '200':
          description: A successful response
          schema:
            type: string 

  /books/{id}:
      get:
        parameters:
        - in: path
          name: id
          type: string
          required: true
          description: Book ID.
        summary: List shelves
        operationId: /:book
        responses:
            '200':
              description: A successful response
              schema:
                type: string

  /books/add:
      post:
        parameters:
        - in: path
          name: id
          type: string
          required: true
          description: add book
        summary: List shelves
        operationId: /add
        responses:
            '200':
              description: A successful response
              schema:
                type: string
