name: 'Two-Tier-CloudRun-Firestore'
on:
 workflow_dispatch:
permissions:
  contents: read
  id-token: write
env:
  PROJECT_ID: gbg-sandbox-387923

jobs:
  terraform1:
    name: 'Terraform Bootstrap'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: /home/runner/work/two-tier-cloudrun-firestore/two-tier-cloudrun-firestore/Bootstrap

    steps:

    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      
    - name: Get Secrets
      id: secretdata
      uses: hashicorp/vault-action@v2.5.0
      with:
          url: ${{ secrets.VAULT_ADDR }}
          role: gbg-coe-role-two-tier-cloudrun-firestore
          method: jwt
          path: gbg-coe-auth-two-tier-cloudrun-firestore
          tlsSkipVerify: true
          secrets: |
            gbg-coe-secret-two-tier-cloudrun-firestore/sa_key GOOGLE_CREDENTIALS
  
    - name: Terraform Init
      run: terraform init
      env:
        GOOGLE_CREDENTIALS: ${{ env.GOOGLE_CREDENTIALS }}
        
    - name: Terraform Validate
      run: terraform validate
      
    - name: Terraform Fmt
      run: terraform fmt
        
    - name: Terraform Plan
      run: terraform plan
      env:
        GOOGLE_CREDENTIALS: ${{ env.GOOGLE_CREDENTIALS }}
        
    - name: Terraform Apply
      run: terraform apply -auto-approve
      env:
        GOOGLE_CREDENTIALS: ${{ env.GOOGLE_CREDENTIALS }}  

  terraform2:
    name: 'Image_Build'
    runs-on: ubuntu-latest
    needs: terraform1
    defaults:
      run:
        shell: bash
        working-directory: /home/runner/work/two-tier-cloudrun-firestore/two-tier-cloudrun-firestore

    steps:
            
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Get Secrets
        id: secretdata
        uses: hashicorp/vault-action@v2.5.0
        with:
            url: ${{ secrets.VAULT_ADDR }}
            role: gbg-coe-role-two-tier-cloudrun-firestore
            method: jwt
            path: gbg-coe-auth-two-tier-cloudrun-firestore
            tlsSkipVerify: true
            secrets: |
              gbg-coe-secret-two-tier-cloudrun-firestore/sa_key GOOGLE_CREDENTIALS

      - name: gcloud 
        uses: google-github-actions/setup-gcloud@94337306dda8180d967a56932ceb4ddcf01edae7
        with:
          service_account_key: ${{ env.GOOGLE_CREDENTIALS }}

      - run: |-
          gcloud --quiet auth configure-docker

      - name: Cloning the repository, docker build and push
        run: |
            git clone https://github.com/GoogleCloudPlatform/nodejs-getting-started.git
            cd nodejs-getting-started/bookshelf
            docker build -t gcr.io/${{env.PROJECT_ID}}/app .
            docker push gcr.io/${{env.PROJECT_ID}}/app    
    
      - run: |-
            gcloud --quiet auth configure-docker  

  terraform3:
    name: 'Terraform First Deployment'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: /home/runner/work/two-tier-cloudrun-firestore/two-tier-cloudrun-firestore/first-deployment

    needs: terraform2
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
      
      - name: Get Secrets
        id: secretdata
        uses: hashicorp/vault-action@v2.5.0
        with:
            url: ${{ secrets.VAULT_ADDR }}
            role: gbg-coe-role-two-tier-cloudrun-firestore
            method: jwt
            path: gbg-coe-auth-two-tier-cloudrun-firestore
            tlsSkipVerify: true
            secrets: |
              gbg-coe-secret-two-tier-cloudrun-firestore/sa_key GOOGLE_CREDENTIALS
        
      - name: Get Secrets
        id: secretdata1
        uses: hashicorp/vault-action@v2.5.0
        with:
          url: ${{ secrets.VAULT_ADDR }}
          role: gbg-coe-role-two-tier-cloudrun-firestore-github
          method: jwt
          path: gbg-coe-auth-two-tier-cloudrun-firestore-github
          tlsSkipVerify: true
          secrets: |
            gbg-coe-secret-two-tier-cloudrun-firestore-github/access_key ACCESS_CREDENTIALS
      
      - name: Pull private Terraform code
        run: |
       
          git config --global url."https://"${{env.ACCESS_CREDENTIALS}}"@github.com/".insteadOf "https://github.com"
       
      - name: Terraform Init
        run: terraform init
        env:
          GOOGLE_CREDENTIALS: ${{ env.GOOGLE_CREDENTIALS }}    
      

      - name: Terraform Validate
        run: terraform validate
        env:
          GOOGLE_CREDENTIALS: ${{ env.GOOGLE_CREDENTIALS }} 

      - name: Terraform Plan
        id: plan
        run: terraform plan 
        env:
          GOOGLE_CREDENTIALS: ${{ env.GOOGLE_CREDENTIALS }} 

      - name: Terraform Apply
        run: terraform apply -auto-approve
        env:
          GOOGLE_CREDENTIALS: ${{ env.GOOGLE_CREDENTIALS }} 


  terraform4:
    name: 'Terraform Second Deployment'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: /home/runner/work/two-tier-cloudrun-firestore/two-tier-cloudrun-firestore/second-deployment
    
    needs: terraform3
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
      
      - name: Get Secrets
        id: secretdata
        uses: hashicorp/vault-action@v2.5.0
        with:
            url: ${{ secrets.VAULT_ADDR }}
            role: gbg-coe-role-two-tier-cloudrun-firestore
            method: jwt
            path: gbg-coe-auth-two-tier-cloudrun-firestore
            tlsSkipVerify: true
            secrets: |
              gbg-coe-secret-two-tier-cloudrun-firestore/sa_key GOOGLE_CREDENTIALS
        
      - name: Get Secrets
        id: secretdata1
        uses: hashicorp/vault-action@v2.5.0
        with:
          url: ${{ secrets.VAULT_ADDR }}
          role: gbg-coe-role-two-tier-cloudrun-firestore-github
          method: jwt
          path: gbg-coe-auth-two-tier-cloudrun-firestore-github
          tlsSkipVerify: true
          secrets: |
            gbg-coe-secret-two-tier-cloudrun-firestore-github/access_key ACCESS_CREDENTIALS
      
      - name: Pull private Terraform code
        run: |
       
          git config --global url."https://"${{env.ACCESS_CREDENTIALS}}"@github.com/".insteadOf "https://github.com"
      
      - name: gcloud 
        uses: google-github-actions/setup-gcloud@94337306dda8180d967a56932ceb4ddcf01edae7
        with:
          service_account_key: ${{ env.GOOGLE_CREDENTIALS }}
        
      - name: env config 
        run: |
          export URL=$(gcloud run services describe book-shelf-app-001 --region=us-central1 --format='value(status.url)' --project=${{env.PROJECT_ID}}) 
          echo $URL
          sed -i "s|CLOUDRUN_URL|$URL|g" spec.yaml
        env:
          GOOGLE_CREDENTIALS: ${{ env.GOOGLE_CREDENTIALS }} 
          
      - name: Terraform Init
        run: terraform init
        env:
          GOOGLE_CREDENTIALS: ${{ env.GOOGLE_CREDENTIALS }}    
      

      - name: Terraform Validate
        run: terraform validate
        env:
          GOOGLE_CREDENTIALS: ${{ env.GOOGLE_CREDENTIALS }} 

      - name: Terraform Plan
        id: plan
        run: terraform plan 
        env:
          GOOGLE_CREDENTIALS: ${{ env.GOOGLE_CREDENTIALS }} 

      - name: Terraform Apply
        run: terraform apply -auto-approve
        env:
          GOOGLE_CREDENTIALS: ${{ env.GOOGLE_CREDENTIALS }} 
