name: DESTROY
on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  terraform1:
    name: 'Terraform destroy: first-deployment'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: /home/runner/work/CloudRun-API-Firestore/CloudRun-API-Firestore/first-deployment
    steps:
     
      - name: Checkout
        uses: actions/checkout@v2

      - name: Terraform Init
        run: terraform init
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Fmt
        run: terraform fmt

      - name: Terraform Plan
        id: plan
        run: terraform plan 

      - name: Terraform Destroy
        run: terraform destroy -auto-approve

  terraform2:
    name: 'Terraform destroy: second-deployment'
    runs-on: ubuntu-latest
    needs: terraform1
    defaults:
      run:
        shell: bash
        working-directory: /home/runner/work/CloudRun-API-Firestore/CloudRun-API-Firestore/second-deployment
    steps:
     
      - name: Checkout
        uses: actions/checkout@v2

      - name: Terraform Init
        run: terraform init
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Fmt
        run: terraform fmt

      - name: Terraform Plan
        id: plan
        run: terraform plan 

      - name: Terraform Destroy
        run: terraform destroy -auto-approve