name: 'Destroy'

on:
  workflow_dispatch:
permissions:
  contents: read
  id-token: write

jobs:
        
  terraform1:
    name: 'Two-Tier-CloudRun-first-deployment-Destroy'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: /home/runner/work/CloudRun-API-Firestore/CloudRun-API-Firestore/first-deployment

    steps:
      - name: Checkout code
        uses: actions/checkout@v2 
     
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}  
      
      - name: Terraform Validate
        run: terraform validate
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

      - name: Terraform Destroy
        run: terraform destroy -auto-approve
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}


  terraform2:
    name: 'Two-Tier-CloudRun-second-deployment-Destroy'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: /home/runner/work/CloudRun-API-Firestore/CloudRun-API-Firestore/second-deployment

    steps:
      - name: Checkout code
        uses: actions/checkout@v2 
     
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}  
      
      - name: Terraform Validate
        run: terraform validate
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

      - name: Terraform Destroy
        run: terraform destroy -auto-approve
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
